### ISSUE TITLE
open graph 수정 필요

### ISSUE THREAD

**Issue by hwasurr** [whileTrueDev/tp-mvp#248]
![image](https://user-images.githubusercontent.com/43170520/118093998-272e8e80-b409-11eb-978f-76614bf19aea.png)

로고 이미지, 설명글 등 수정 필요

**Comment by jiyeon2** [comment]
<img width="599" alt="스크린샷 2021-07-22 오후 2 36 05" src="https://user-images.githubusercontent.com/18395475/126594045-24231a3c-4b5a-4a68-8127-7b081b5cec24.png">
로 수정하였습니다
